#!/bin/sh
# Generate a C header embedding one or more files as byte arrays.
#
# apibridge/main.c deliberately points civetweb's document_root at
# "/nonexistent" to keep the exposed HTTP surface limited to explicitly
# registered "/api/v1/..." handlers (see the comment there). Static docs
# assets (the OpenAPI spec, the Redoc HTML shell, the vendored Redoc JS
# bundle) are compiled into the apibridged binary instead and served by
# their own explicit handlers in apibridge/httpapi.c, rather than reopening
# generic static-file serving.
#
# Portable POSIX (od + awk), deliberately not requiring python or xxd at
# build time.
#
# Usage: embed_file.sh OUT.h SYMBOL1=FILE1 [SYMBOL2=FILE2 ...]
set -e

out="$1"
shift

tmp="${out}.tmp"
{
	echo "/* Generated by tools/embed_file.sh - do not edit. */"
	echo "#include <stddef.h>"
	echo

	for pair in "$@"; do
		symbol="${pair%%=*}"
		file="${pair#*=}"
		echo "static const unsigned char ${symbol}[] = {"
		od -An -v -tx1 "$file" | awk '{ for (i = 1; i <= NF; i++) printf "0x%s, ", $i; print "" }'
		echo "};"
		echo "static const size_t ${symbol}_len = sizeof(${symbol});"
		echo
	done
} >"$tmp"
mv "$tmp" "$out"
